version: "3.9"
services:
  web:
    build: .
    ports:
      - "9709:3000"
  dev:
    image: node:14.17.1-alpine
    command: sh -c "
      yarn set version berry &&
      yarn &&
      yarn dev"
    ports:
      - 9708:3000
    working_dir: /workspace
    volumes:
      - ./:/workspace